/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AppSearchRouteImport } from './routes/_app/search'
import { Route as AppReviewRouteImport } from './routes/_app/review'
import { Route as AppContextPackRouteImport } from './routes/_app/context-pack'
import { Route as AppMemoryIndexRouteImport } from './routes/_app/memory/index'
import { Route as AppMemoryIdRouteImport } from './routes/_app/memory/$id'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppSearchRoute = AppSearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => AppRoute,
} as any)
const AppReviewRoute = AppReviewRouteImport.update({
  id: '/review',
  path: '/review',
  getParentRoute: () => AppRoute,
} as any)
const AppContextPackRoute = AppContextPackRouteImport.update({
  id: '/context-pack',
  path: '/context-pack',
  getParentRoute: () => AppRoute,
} as any)
const AppMemoryIndexRoute = AppMemoryIndexRouteImport.update({
  id: '/memory/',
  path: '/memory/',
  getParentRoute: () => AppRoute,
} as any)
const AppMemoryIdRoute = AppMemoryIdRouteImport.update({
  id: '/memory/$id',
  path: '/memory/$id',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/login': typeof LoginRoute
  '/context-pack': typeof AppContextPackRoute
  '/review': typeof AppReviewRoute
  '/search': typeof AppSearchRoute
  '/memory/$id': typeof AppMemoryIdRoute
  '/memory/': typeof AppMemoryIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/context-pack': typeof AppContextPackRoute
  '/review': typeof AppReviewRoute
  '/search': typeof AppSearchRoute
  '/': typeof AppIndexRoute
  '/memory/$id': typeof AppMemoryIdRoute
  '/memory': typeof AppMemoryIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/_app/context-pack': typeof AppContextPackRoute
  '/_app/review': typeof AppReviewRoute
  '/_app/search': typeof AppSearchRoute
  '/_app/': typeof AppIndexRoute
  '/_app/memory/$id': typeof AppMemoryIdRoute
  '/_app/memory/': typeof AppMemoryIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/context-pack'
    | '/review'
    | '/search'
    | '/memory/$id'
    | '/memory/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/context-pack'
    | '/review'
    | '/search'
    | '/'
    | '/memory/$id'
    | '/memory'
  id:
    | '__root__'
    | '/_app'
    | '/login'
    | '/_app/context-pack'
    | '/_app/review'
    | '/_app/search'
    | '/_app/'
    | '/_app/memory/$id'
    | '/_app/memory/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/search': {
      id: '/_app/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof AppSearchRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/review': {
      id: '/_app/review'
      path: '/review'
      fullPath: '/review'
      preLoaderRoute: typeof AppReviewRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/context-pack': {
      id: '/_app/context-pack'
      path: '/context-pack'
      fullPath: '/context-pack'
      preLoaderRoute: typeof AppContextPackRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/memory/': {
      id: '/_app/memory/'
      path: '/memory'
      fullPath: '/memory/'
      preLoaderRoute: typeof AppMemoryIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/memory/$id': {
      id: '/_app/memory/$id'
      path: '/memory/$id'
      fullPath: '/memory/$id'
      preLoaderRoute: typeof AppMemoryIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppContextPackRoute: typeof AppContextPackRoute
  AppReviewRoute: typeof AppReviewRoute
  AppSearchRoute: typeof AppSearchRoute
  AppIndexRoute: typeof AppIndexRoute
  AppMemoryIdRoute: typeof AppMemoryIdRoute
  AppMemoryIndexRoute: typeof AppMemoryIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppContextPackRoute: AppContextPackRoute,
  AppReviewRoute: AppReviewRoute,
  AppSearchRoute: AppSearchRoute,
  AppIndexRoute: AppIndexRoute,
  AppMemoryIdRoute: AppMemoryIdRoute,
  AppMemoryIndexRoute: AppMemoryIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
